# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0005_auto_20170223_1531'),
        ('log', '0004_auto_20170104_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lecturer.University'),
            preserve_default=False,
        ),
    ]
