# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
