# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_university_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.University')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('name', 'university')]),
        ),
    ]
