# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0005_auto_20170223_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'lecturer')]),
        ),
    ]
