# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0006_auto_20170301_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('user', 'lecturer')]),
        ),
    ]
