# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0007_auto_20170302_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
