# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0009_comment_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_score_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
